-- Reviewed request-aware lifestyle scenes for the six approved men.
INSERT INTO ai_companion_photo_assets (id, user_id, companion_id, visual_identity_version, object_key, metadata_json, generation_source, status, created_at, updated_at, appearance_catalog_id, scene_fingerprint)
VALUES
  ('aiphoto_asset_bank_arjun_cozy_v1', NULL, 'aic_male_catalog_draft_arjun_v1', 1, 'catalog/bank/v1/appearance_male_arjun_v1/cozy-evening/02-lifestyle.png', json_object('approved', true, 'scene', 'cozy-evening', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/private/drafts/men-v1/arjun/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'appearance_male_arjun_v1', 'bank-cozy-evening-v1'),
  ('aiphoto_asset_bank_arjun_date_v1', NULL, 'aic_male_catalog_draft_arjun_v1', 1, 'catalog/bank/v1/appearance_male_arjun_v1/date-night/03-lifestyle.png', json_object('approved', true, 'scene', 'date-night', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/private/drafts/men-v1/arjun/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'appearance_male_arjun_v1', 'bank-date-night-v1'),
  ('aiphoto_asset_bank_arjun_outdoor_v1', NULL, 'aic_male_catalog_draft_arjun_v1', 1, 'catalog/bank/v1/appearance_male_arjun_v1/outdoor-daytime/04-lifestyle.png', json_object('approved', true, 'scene', 'outdoor-daytime', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/private/drafts/men-v1/arjun/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'appearance_male_arjun_v1', 'bank-outdoor-daytime-v1'),
  ('aiphoto_asset_bank_diego_cozy_v1', NULL, 'aic_male_catalog_draft_diego_v1', 1, 'catalog/bank/v1/appearance_male_diego_v1/cozy-evening/02-lifestyle.png', json_object('approved', true, 'scene', 'cozy-evening', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/private/drafts/men-v1/diego/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'appearance_male_diego_v1', 'bank-cozy-evening-v1'),
  ('aiphoto_asset_bank_diego_date_v1', NULL, 'aic_male_catalog_draft_diego_v1', 1, 'catalog/bank/v1/appearance_male_diego_v1/date-night/03-lifestyle.png', json_object('approved', true, 'scene', 'date-night', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/private/drafts/men-v1/diego/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'appearance_male_diego_v1', 'bank-date-night-v1'),
  ('aiphoto_asset_bank_diego_outdoor_v1', NULL, 'aic_male_catalog_draft_diego_v1', 1, 'catalog/bank/v1/appearance_male_diego_v1/outdoor-daytime/04-lifestyle.png', json_object('approved', true, 'scene', 'outdoor-daytime', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/private/drafts/men-v1/diego/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'appearance_male_diego_v1', 'bank-outdoor-daytime-v1'),
  ('aiphoto_asset_bank_kenji_cozy_v1', NULL, 'aic_male_catalog_draft_kenji_v1', 1, 'catalog/bank/v1/appearance_male_kenji_v1/cozy-evening/02-lifestyle.png', json_object('approved', true, 'scene', 'cozy-evening', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/private/drafts/men-v1/kenji/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'appearance_male_kenji_v1', 'bank-cozy-evening-v1'),
  ('aiphoto_asset_bank_kenji_date_v1', NULL, 'aic_male_catalog_draft_kenji_v1', 1, 'catalog/bank/v1/appearance_male_kenji_v1/date-night/03-lifestyle.png', json_object('approved', true, 'scene', 'date-night', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/private/drafts/men-v1/kenji/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'appearance_male_kenji_v1', 'bank-date-night-v1'),
  ('aiphoto_asset_bank_kenji_outdoor_v1', NULL, 'aic_male_catalog_draft_kenji_v1', 1, 'catalog/bank/v1/appearance_male_kenji_v1/outdoor-daytime/04-lifestyle.png', json_object('approved', true, 'scene', 'outdoor-daytime', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/private/drafts/men-v1/kenji/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'appearance_male_kenji_v1', 'bank-outdoor-daytime-v1'),
  ('aiphoto_asset_bank_malik_cozy_v1', NULL, 'aic_male_catalog_draft_malik_v1', 1, 'catalog/bank/v1/appearance_male_malik_v1/cozy-evening/02-lifestyle.png', json_object('approved', true, 'scene', 'cozy-evening', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/private/drafts/men-v1/malik/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'appearance_male_malik_v1', 'bank-cozy-evening-v1'),
  ('aiphoto_asset_bank_malik_date_v1', NULL, 'aic_male_catalog_draft_malik_v1', 1, 'catalog/bank/v1/appearance_male_malik_v1/date-night/03-lifestyle.png', json_object('approved', true, 'scene', 'date-night', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/private/drafts/men-v1/malik/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'appearance_male_malik_v1', 'bank-date-night-v1'),
  ('aiphoto_asset_bank_malik_outdoor_v1', NULL, 'aic_male_catalog_draft_malik_v1', 1, 'catalog/bank/v1/appearance_male_malik_v1/outdoor-daytime/04-lifestyle.png', json_object('approved', true, 'scene', 'outdoor-daytime', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/private/drafts/men-v1/malik/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'appearance_male_malik_v1', 'bank-outdoor-daytime-v1'),
  ('aiphoto_asset_bank_oliver_cozy_v1', NULL, 'aic_male_catalog_draft_oliver_v1', 1, 'catalog/bank/v1/appearance_male_oliver_v1/cozy-evening/02-lifestyle.png', json_object('approved', true, 'scene', 'cozy-evening', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/private/drafts/men-v1/oliver/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'appearance_male_oliver_v1', 'bank-cozy-evening-v1'),
  ('aiphoto_asset_bank_oliver_date_v1', NULL, 'aic_male_catalog_draft_oliver_v1', 1, 'catalog/bank/v1/appearance_male_oliver_v1/date-night/03-lifestyle.png', json_object('approved', true, 'scene', 'date-night', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/private/drafts/men-v1/oliver/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'appearance_male_oliver_v1', 'bank-date-night-v1'),
  ('aiphoto_asset_bank_oliver_outdoor_v1', NULL, 'aic_male_catalog_draft_oliver_v1', 1, 'catalog/bank/v1/appearance_male_oliver_v1/outdoor-daytime/04-lifestyle.png', json_object('approved', true, 'scene', 'outdoor-daytime', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/private/drafts/men-v1/oliver/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'appearance_male_oliver_v1', 'bank-outdoor-daytime-v1'),
  ('aiphoto_asset_bank_samir_cozy_v1', NULL, 'aic_male_catalog_draft_samir_v1', 1, 'catalog/bank/v1/appearance_male_samir_v1/cozy-evening/02-lifestyle.png', json_object('approved', true, 'scene', 'cozy-evening', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/private/drafts/men-v1/samir/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'appearance_male_samir_v1', 'bank-cozy-evening-v1'),
  ('aiphoto_asset_bank_samir_date_v1', NULL, 'aic_male_catalog_draft_samir_v1', 1, 'catalog/bank/v1/appearance_male_samir_v1/date-night/03-lifestyle.png', json_object('approved', true, 'scene', 'date-night', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/private/drafts/men-v1/samir/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'appearance_male_samir_v1', 'bank-date-night-v1'),
  ('aiphoto_asset_bank_samir_outdoor_v1', NULL, 'aic_male_catalog_draft_samir_v1', 1, 'catalog/bank/v1/appearance_male_samir_v1/outdoor-daytime/04-lifestyle.png', json_object('approved', true, 'scene', 'outdoor-daytime', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/private/drafts/men-v1/samir/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'appearance_male_samir_v1', 'bank-outdoor-daytime-v1')
ON CONFLICT(id) DO UPDATE SET object_key=excluded.object_key, metadata_json=excluded.metadata_json, generation_source=excluded.generation_source, status=excluded.status, updated_at=excluded.updated_at, appearance_catalog_id=excluded.appearance_catalog_id, scene_fingerprint=excluded.scene_fingerprint;
