-- Reviewed request-aware lifestyle scenes for the five remaining approved women.
INSERT INTO ai_companion_photo_assets (id, user_id, companion_id, visual_identity_version, object_key, metadata_json, generation_source, status, created_at, updated_at, appearance_catalog_id, scene_fingerprint)
VALUES
  ('aiphoto_asset_bank_alexa_cozy_v1', NULL, 'aic_4562251e-b22c-4fb0-98c5-f5ecb8a73e94', 1, 'catalog/bank/v1/catalog-alexa/cozy-evening/02-lifestyle.png', json_object('approved', true, 'scene', 'cozy-evening', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/approved/v1/alexa/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'catalog-alexa', 'bank-cozy-evening-v1'),
  ('aiphoto_asset_bank_alexa_date_v1', NULL, 'aic_4562251e-b22c-4fb0-98c5-f5ecb8a73e94', 1, 'catalog/bank/v1/catalog-alexa/date-night/03-lifestyle.png', json_object('approved', true, 'scene', 'date-night', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/approved/v1/alexa/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'catalog-alexa', 'bank-date-night-v1'),
  ('aiphoto_asset_bank_alexa_outdoor_v1', NULL, 'aic_4562251e-b22c-4fb0-98c5-f5ecb8a73e94', 1, 'catalog/bank/v1/catalog-alexa/outdoor-daytime/04-lifestyle.png', json_object('approved', true, 'scene', 'outdoor-daytime', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/approved/v1/alexa/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'catalog-alexa', 'bank-outdoor-daytime-v1'),
  ('aiphoto_asset_bank_lisa_cozy_v1', NULL, 'aic_c2052139-b98b-4933-ad59-75b22380bcd1', 1, 'catalog/bank/v1/catalog-lisa/cozy-evening/02-lifestyle.png', json_object('approved', true, 'scene', 'cozy-evening', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/approved/v1/lisa/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'catalog-lisa', 'bank-cozy-evening-v1'),
  ('aiphoto_asset_bank_lisa_date_v1', NULL, 'aic_c2052139-b98b-4933-ad59-75b22380bcd1', 1, 'catalog/bank/v1/catalog-lisa/date-night/03-lifestyle.png', json_object('approved', true, 'scene', 'date-night', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/approved/v1/lisa/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'catalog-lisa', 'bank-date-night-v1'),
  ('aiphoto_asset_bank_lisa_outdoor_v1', NULL, 'aic_c2052139-b98b-4933-ad59-75b22380bcd1', 1, 'catalog/bank/v1/catalog-lisa/outdoor-daytime/04-lifestyle.png', json_object('approved', true, 'scene', 'outdoor-daytime', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/approved/v1/lisa/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'catalog-lisa', 'bank-outdoor-daytime-v1'),
  ('aiphoto_asset_bank_lora_cozy_v1', NULL, 'aic_5270f5c3-a983-41a1-8ef5-4ccd3027c769', 1, 'catalog/bank/v1/catalog-lora/cozy-evening/02-lifestyle.png', json_object('approved', true, 'scene', 'cozy-evening', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/approved/v1/lora/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'catalog-lora', 'bank-cozy-evening-v1'),
  ('aiphoto_asset_bank_lora_date_v1', NULL, 'aic_5270f5c3-a983-41a1-8ef5-4ccd3027c769', 1, 'catalog/bank/v1/catalog-lora/date-night/03-lifestyle.png', json_object('approved', true, 'scene', 'date-night', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/approved/v1/lora/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'catalog-lora', 'bank-date-night-v1'),
  ('aiphoto_asset_bank_lora_outdoor_v1', NULL, 'aic_5270f5c3-a983-41a1-8ef5-4ccd3027c769', 1, 'catalog/bank/v1/catalog-lora/outdoor-daytime/04-lifestyle.png', json_object('approved', true, 'scene', 'outdoor-daytime', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/approved/v1/lora/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'catalog-lora', 'bank-outdoor-daytime-v1'),
  ('aiphoto_asset_bank_monica_cozy_v1', NULL, 'aic_6c99a138-52b4-475d-ad7d-5d832ab89f77', 1, 'catalog/bank/v1/catalog-monica/cozy-evening/02-lifestyle.png', json_object('approved', true, 'scene', 'cozy-evening', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/approved/v1/monica/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'catalog-monica', 'bank-cozy-evening-v1'),
  ('aiphoto_asset_bank_monica_date_v1', NULL, 'aic_6c99a138-52b4-475d-ad7d-5d832ab89f77', 1, 'catalog/bank/v1/catalog-monica/date-night/03-lifestyle.png', json_object('approved', true, 'scene', 'date-night', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/approved/v1/monica/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'catalog-monica', 'bank-date-night-v1'),
  ('aiphoto_asset_bank_monica_outdoor_v1', NULL, 'aic_6c99a138-52b4-475d-ad7d-5d832ab89f77', 1, 'catalog/bank/v1/catalog-monica/outdoor-daytime/04-lifestyle.png', json_object('approved', true, 'scene', 'outdoor-daytime', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/approved/v1/monica/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'catalog-monica', 'bank-outdoor-daytime-v1'),
  ('aiphoto_asset_bank_sarah_cozy_v1', NULL, 'aic_d0a68b1d-0ad9-46c6-a103-54dc71e8214d', 1, 'catalog/bank/v1/catalog-sarah/cozy-evening/02-lifestyle.png', json_object('approved', true, 'scene', 'cozy-evening', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/approved/v1/sarah/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'catalog-sarah', 'bank-cozy-evening-v1'),
  ('aiphoto_asset_bank_sarah_date_v1', NULL, 'aic_d0a68b1d-0ad9-46c6-a103-54dc71e8214d', 1, 'catalog/bank/v1/catalog-sarah/date-night/03-lifestyle.png', json_object('approved', true, 'scene', 'date-night', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/approved/v1/sarah/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'catalog-sarah', 'bank-date-night-v1'),
  ('aiphoto_asset_bank_sarah_outdoor_v1', NULL, 'aic_d0a68b1d-0ad9-46c6-a103-54dc71e8214d', 1, 'catalog/bank/v1/catalog-sarah/outdoor-daytime/04-lifestyle.png', json_object('approved', true, 'scene', 'outdoor-daytime', 'syntheticProvenance', 'imagegen', 'identityReference', 'catalog/approved/v1/sarah/canonical.png'), 'imagegen-approved-v2', 'approved', unixepoch()*1000, unixepoch()*1000, 'catalog-sarah', 'bank-outdoor-daytime-v1')
ON CONFLICT(id) DO UPDATE SET object_key=excluded.object_key, metadata_json=excluded.metadata_json, generation_source=excluded.generation_source, status=excluded.status, updated_at=excluded.updated_at, appearance_catalog_id=excluded.appearance_catalog_id, scene_fingerprint=excluded.scene_fingerprint;
