-- Private review seed only. These rows deliberately have no catalog entry, so
-- the customer picker cannot discover them before canonical-pack approval.
INSERT INTO ai_companions (id, user_id, name, identity, persona_key, traits_json, backstory, avatar_key, created_at, updated_at) VALUES
  ('aic_male_catalog_draft_samir_v1', 'e528cd67-87d3-4985-b7ce-c9995ced6795', 'Samir', 'man', 'confident_leader', json_object('warmth', 4, 'playfulness', 3, 'directness', 4, 'replyStyle', 'natural'), '', 'companion-default', unixepoch() * 1000, unixepoch() * 1000),
  ('aic_male_catalog_draft_malik_v1', 'e528cd67-87d3-4985-b7ce-c9995ced6795', 'Malik', 'man', 'supportive_partner', json_object('warmth', 5, 'playfulness', 3, 'directness', 3, 'replyStyle', 'natural'), '', 'companion-default', unixepoch() * 1000, unixepoch() * 1000),
  ('aic_male_catalog_draft_kenji_v1', 'e528cd67-87d3-4985-b7ce-c9995ced6795', 'Kenji', 'man', 'quiet_romantic', json_object('warmth', 4, 'playfulness', 2, 'directness', 3, 'replyStyle', 'short'), '', 'companion-default', unixepoch() * 1000, unixepoch() * 1000),
  ('aic_male_catalog_draft_diego_v1', 'e528cd67-87d3-4985-b7ce-c9995ced6795', 'Diego', 'man', 'playful_tease', json_object('warmth', 4, 'playfulness', 5, 'directness', 3, 'replyStyle', 'natural'), '', 'companion-default', unixepoch() * 1000, unixepoch() * 1000),
  ('aic_male_catalog_draft_arjun_v1', 'e528cd67-87d3-4985-b7ce-c9995ced6795', 'Arjun', 'man', 'personal_growth_companion', json_object('warmth', 4, 'playfulness', 2, 'directness', 4, 'replyStyle', 'detailed'), '', 'companion-default', unixepoch() * 1000, unixepoch() * 1000),
  ('aic_male_catalog_draft_oliver_v1', 'e528cd67-87d3-4985-b7ce-c9995ced6795', 'Oliver', 'man', 'sarcastic_best_friend', json_object('warmth', 3, 'playfulness', 5, 'directness', 4, 'replyStyle', 'natural'), '', 'companion-default', unixepoch() * 1000, unixepoch() * 1000)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  persona_key = excluded.persona_key,
  traits_json = excluded.traits_json,
  updated_at = excluded.updated_at;

INSERT INTO ai_companion_visual_identities (companion_id, appearance_catalog_id, version, status, locked_traits_json, canonical_object_key, reference_object_keys_json, validation_status, validation_notes, created_at, updated_at) VALUES
  ('aic_male_catalog_draft_samir_v1', NULL, 1, 'casting_selected', json_object('identity', 'man', 'apparentAge', '26 to 30 years old', 'hair', 'short textured dark-brown hair', 'eyes', 'warm brown eyes', 'facialStructure', 'defined oval face', 'skinAppearance', 'warm olive complexion', 'build', 'fit, natural adult build', 'distinctiveFeatures', json_array('light stubble', 'calm direct gaze')), 'catalog/private/drafts/men-v1/samir/canonical.png', json_array('catalog/private/drafts/men-v1/samir/canonical.png'), 'manual_review', 'Private male catalog draft awaiting its six-reference canonical pack.', unixepoch() * 1000, unixepoch() * 1000),
  ('aic_male_catalog_draft_malik_v1', NULL, 1, 'casting_selected', json_object('identity', 'man', 'apparentAge', '26 to 30 years old', 'hair', 'close-cropped natural curls', 'eyes', 'deep brown eyes', 'facialStructure', 'strong oval face', 'skinAppearance', 'deep brown complexion', 'build', 'athletic, natural adult build', 'distinctiveFeatures', json_array('neatly shaped beard', 'warm smile')), 'catalog/private/drafts/men-v1/malik/canonical.png', json_array('catalog/private/drafts/men-v1/malik/canonical.png'), 'manual_review', 'Private male catalog draft awaiting its six-reference canonical pack.', unixepoch() * 1000, unixepoch() * 1000),
  ('aic_male_catalog_draft_kenji_v1', NULL, 1, 'casting_selected', json_object('identity', 'man', 'apparentAge', '26 to 30 years old', 'hair', 'softly wavy black hair', 'eyes', 'dark brown eyes', 'facialStructure', 'defined jawline and oval face', 'skinAppearance', 'warm light complexion', 'build', 'lean, natural adult build', 'distinctiveFeatures', json_array('subtle genuine smile', 'softly textured hair')), 'catalog/private/drafts/men-v1/kenji/canonical.png', json_array('catalog/private/drafts/men-v1/kenji/canonical.png'), 'manual_review', 'Private male catalog draft awaiting its six-reference canonical pack.', unixepoch() * 1000, unixepoch() * 1000),
  ('aic_male_catalog_draft_diego_v1', NULL, 1, 'casting_selected', json_object('identity', 'man', 'apparentAge', '26 to 30 years old', 'hair', 'thick curly dark hair', 'eyes', 'hazel eyes', 'facialStructure', 'strong angular oval face', 'skinAppearance', 'sun-warmed olive complexion', 'build', 'fit, natural adult build', 'distinctiveFeatures', json_array('light stubble', 'easy smile')), 'catalog/private/drafts/men-v1/diego/canonical.png', json_array('catalog/private/drafts/men-v1/diego/canonical.png'), 'manual_review', 'Private male catalog draft awaiting its six-reference canonical pack.', unixepoch() * 1000, unixepoch() * 1000),
  ('aic_male_catalog_draft_arjun_v1', NULL, 1, 'casting_selected', json_object('identity', 'man', 'apparentAge', '26 to 30 years old', 'hair', 'short styled black hair', 'eyes', 'rich brown eyes', 'facialStructure', 'defined oval face', 'skinAppearance', 'medium-brown complexion', 'build', 'strong, realistic adult build', 'distinctiveFeatures', json_array('close beard', 'warm composed expression')), 'catalog/private/drafts/men-v1/arjun/canonical.png', json_array('catalog/private/drafts/men-v1/arjun/canonical.png'), 'manual_review', 'Private male catalog draft awaiting its six-reference canonical pack.', unixepoch() * 1000, unixepoch() * 1000),
  ('aic_male_catalog_draft_oliver_v1', NULL, 1, 'casting_selected', json_object('identity', 'man', 'apparentAge', '26 to 30 years old', 'hair', 'tousled medium-brown hair', 'eyes', 'blue-green eyes', 'facialStructure', 'defined oval face', 'skinAppearance', 'fair warm complexion', 'build', 'comfortably athletic adult build', 'distinctiveFeatures', json_array('light stubble', 'playful half-smile')), 'catalog/private/drafts/men-v1/oliver/canonical.png', json_array('catalog/private/drafts/men-v1/oliver/canonical.png'), 'manual_review', 'Private male catalog draft awaiting its six-reference canonical pack.', unixepoch() * 1000, unixepoch() * 1000)
ON CONFLICT(companion_id) DO UPDATE SET
  status = excluded.status,
  locked_traits_json = excluded.locked_traits_json,
  canonical_object_key = excluded.canonical_object_key,
  reference_object_keys_json = excluded.reference_object_keys_json,
  validation_status = excluded.validation_status,
  validation_notes = excluded.validation_notes,
  updated_at = excluded.updated_at;
