import { drizzle } from "drizzle-orm/d1";

export type EnvBindings = {
  DB: D1Database;
  AI?: Ai;
  COMPANION_IMAGES?: R2Bucket;
  COMPANION_AUDIO?: R2Bucket;
  APP_NAME?: string;
  ADMIN_SECRET?: string;
  VISUAL_IDENTITY_OPERATOR_TOKEN?: string;
  APP_ENV?: string;
  ENABLE_DEV_ENDPOINTS?: string;
  TURNSTILE_SECRET_KEY?: string;
  STRIPE_SECRET_KEY?: string;
  PAYPAL_CLIENT_ID?: string;
  PAYPAL_SECRET?: string;
  PAYPAL_ENV?: string;
  PAYPAL_WEBHOOK_ID?: string;
  PAYMENTS_PROVIDER?: string;
  RESEND_API_KEY?: string;
  RESEND_FROM_EMAIL?: string;
  RESEND_FROM_NAME?: string;
  RESEND_SUPPORT_FROM_EMAIL?: string;
  SUPPORT_REPLY_TO_EMAIL?: string;
  APPLE_BUNDLE_ID?: string;
  APPLE_SHARED_SECRET?: string;
  GOOGLE_PLAY_PACKAGE_NAME?: string;
  GOOGLE_PLAY_SERVICE_ACCOUNT_JSON?: string;
  PAYPAL_AI_PRO_PLAN_ID?: string;
  PAYPAL_AI_ULTRA_PLAN_ID?: string;
  FIREBASE_PROJECT_ID?: string;
  FIREBASE_SERVICE_ACCOUNT_JSON?: string;
  AI_COMPANION_ENABLED?: string;
  AI_COMPANION_DAILY_TRIAL_LIMIT?: string;
  AI_COMPANION_BETA_EMAILS?: string;
  AI_COMPANION_COMPLIMENTARY_PRO_EMAILS?: string;
  AI_COMPANION_COMPLIMENTARY_ULTRA_EMAILS?: string;
  AI_COMPANION_VOICE_ENABLED?: string;
  AI_COMPANION_CALLS_ENABLED?: string;
  GOOGLE_TTS_SERVICE_ACCOUNT_JSON?: string;
  COMPANION_IDENTITY_EVALUATOR_URL?: string;
  COMPANION_IDENTITY_EVALUATOR_TOKEN?: string;
  COMPANION_IDENTITY_MIN_SCORE?: string;
  AI_COMPANION_PHOTO_FREE_LIFETIME_GENERATION_LIMIT?: string;
  AI_COMPANION_PHOTO_PRO_DAILY_GENERATION_LIMIT?: string;
  AI_COMPANION_PHOTO_ULTRA_DAILY_GENERATION_LIMIT?: string;
  AI_COMPANION_PHOTO_ESTIMATED_COST_CENTS?: string;
  AI_COMPANION_PHOTO_MONTHLY_SPEND_CEILING_CENTS?: string;
};

export function getDb(env: EnvBindings) {
  return drizzle(env.DB);
}
